esphome:
  name: sterowanie-nawadniania

esp32:
  variant: esp32

wifi:
  ssid: Frutek
  password: Frutek!23

#API do Home Assistant
api:

#update zdalny
ota:
  - platform: esphome

#dostęp po www
web_server:
  port: 80

# LED exposed as binary light
output:
  - platform: gpio
    pin: GPIO23
    id: output_led

i2c:
  sda: 4
  scl: 5
  scan: true
  id: bus_a

light:
  - platform: binary
    id: light_led
    name: LED
    output: output_led

pcf8574:
  - id: "pcf8574_hub_out_1" # for output channel 1-8
    address: 0x24

  - id: "pcf8574_hub_in_1" # for input channel 1-8
    address: 0x22

# Individual outputs
switch:
  - platform: gpio
  #relay 1: pompa 
  #230 V
    id: pompa
    name: "Pompa"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 0
      mode: OUTPUT
      inverted: true

  - platform: gpio
  #relay 2: katalpy, miskany i skrzynia
  #24V
    id: zawor1
    name: "zawor1"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 1
      mode: OUTPUT
      inverted: true

  - platform: gpio
  #relay 3: tuje
  #24V
    id: zawor2
    name: "zawor2"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 2
      mode: OUTPUT
      inverted: true

  - platform: gpio
  #relay 4: hałda
  #24V
    id: zawor3
    name: "zawor3"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 3
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "relay5"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 4
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "relay6"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 5
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "relay7"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 6
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "relay8"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 7
      mode: OUTPUT
      inverted: true

binary_sensor:
  - platform: gpio
  #input 1
    #name: "nawadnianie_przycisk"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 0
      mode: INPUT
      inverted: true
    name: "Włącz nawadnianie"
    on_press:
      then:
        - sprinkler.start_full_cycle: nawadnianie

  - platform: gpio
    name: "input2"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 1
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "input3"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 2
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "input4"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 3
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "input5"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 4
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "input6"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 5
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "input7"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 6
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "input8"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 7
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "s3"
    pin:
      number: 32
      inverted: true

  - platform: gpio
    name: "s4"
    pin:
      number: 33
      inverted: true

sprinkler:
  - id: nawadnianie
    main_switch: "Nawadnianie"
    valve_overlap: 3s
    pump_start_pump_delay: 3s
    pump_stop_valve_delay: 3s
    auto_advance_switch: "Normalny cykl"
    valves:
      - valve_switch: "Rośliny"
        enable_switch: "Podlewaj rośliny"
        run_duration: 15min
        valve_switch_id: zawor1
        pump_switch_id: pompa   
      - valve_switch: "Tuje"
        enable_switch: "Podlewaj tuje"
        run_duration: 40min
        valve_switch_id: zawor2
        pump_switch_id: pompa   
      - valve_switch: "Hałda"
        enable_switch: "Podlewaj hałdę"
        run_duration: 40min
        valve_switch_id: zawor3
        pump_switch_id: pompa   

time:
  - platform: sntp
    timezone: "Europe/Warsaw"
    on_time:
      # everyday at 2am
      - hours: 2
        then: 
          - sprinkler.start_full_cycle: nawadnianie    name: LED
    output: output_led

pcf8574:
  - id: "pcf8574_hub_out_1" # for output channel 1-8
    address: 0x24

  - id: "pcf8574_hub_in_1" # for input channel 1-8
    address: 0x22

# Individual outputs
switch:
  - platform: gpio
  #relay 1: pompa 
  #230 V
    id: pompa
    name: "Pompa"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 0
      mode: OUTPUT
      inverted: true

  - platform: gpio
  #relay 2: katalpy, miskany i skrzynia
  #24V
    id: zawor1
    name: "zawor1"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 1
      mode: OUTPUT
      inverted: true

  - platform: gpio
  #relay 3: tuje
  #24V
    id: zawor2
    name: "zawor2"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 2
      mode: OUTPUT
      inverted: true

  - platform: gpio
  #relay 4: hałda
  #24V
    id: zawor3
    name: "zawor3"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 3
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "relay5"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 4
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "relay6"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 5
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "relay7"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 6
      mode: OUTPUT
      inverted: true

  - platform: gpio
    name: "relay8"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 7
      mode: OUTPUT
      inverted: true

binary_sensor:
  - platform: gpio
  #input 1
    #name: "nawadnianie_przycisk"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 0
      mode: INPUT
      inverted: true
    name: "Włącz nawadnianie"
    on_press:
      then:
        - sprinkler.start_full_cycle: nawadnianie

  - platform: gpio
    name: "input2"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 1
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "input3"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 2
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "input4"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 3
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "input5"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 4
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "input6"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 5
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "input7"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 6
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "input8"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 7
      mode: INPUT
      inverted: true

  - platform: gpio
    name: "s3"
    pin:
      number: 32
      inverted: true

  - platform: gpio
    name: "s4"
    pin:
      number: 33
      inverted: true

sprinkler:
  - id: nawadnianie
    main_switch: "Nawadnianie"
    valve_overlap: 3s
    pump_start_pump_delay: 3s
    pump_stop_valve_delay: 3s
    auto_advance_switch: "Normalny cykl"
    valves:
      - valve_switch: "Rośliny"
        enable_switch: "Podlewaj rośliny"
        run_duration: 15min
        valve_switch_id: zawor1
        pump_switch_id: pompa   
      - valve_switch: "Tuje"
        enable_switch: "Podlewaj tuje"
        run_duration: 40min
        valve_switch_id: zawor2
        pump_switch_id: pompa   
      - valve_switch: "Hałda"
        enable_switch: "Podlewaj hałdę"
        run_duration: 40min
        valve_switch_id: zawor3
        pump_switch_id: pompa   

time:
  - platform: sntp
    timezone: "Europe/Warsaw"
    on_time:
      # everyday at 2am
      - hours: 2
        then: 
          - sprinkler.start_full_cycle: nawadnianie
